version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "8091:8091"
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    command: influxd
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb