version: '3.8'
services:
  database:
    container_name: infuxdb
    image: influxdb_image
    restart: always
    ports:
      - 8086:8086
    environment:
      - HOST=0.0.0.0
      - PORT= 80:8086
    build: 
      context: .
      dockerfile: influxdb/Dockerfile
    networks:
      default:
        aliases:
          - influxdb

  broker:
    container_name: rabbit
    image: rabbit_image
    restart: always
    ports:
      - 1883:1883
      - 15672:15672
      - 5672:5672
    environment:
      - HOST=0.0.0.0
      - PORT= 80:1883
    build: 
      context: .
      dockerfile: rabbit/Dockerfile

  visualizador:
    container_name: grafana
    image: grafana_image
    restart: always
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT= 80:3000
    build: 
      context: .
      dockerfile: grafana/Dockerfile

  telegraf:
    image: telegraf:1.25.0
    container_name: telegraf
    restart: always
    environment:
      - INFLUX_TOKEN=2yXwIbUCRxv7QLBnCSeuyhq2l1mMksQWkykADbQUDry7rDDxiBbltDox4P4E0V8aWFOCum6r01nhq3IXuq6HRg==
    command: --config http://influxdb:8086/api/v2/telegrafs/0aaa821d671f4000
    depends_on:
      - database